const countries = [
  { id: 1, name: "Andorra", image: "assets/flags/ad.png" },
  { id: 2, name: "United Arab Emirates", image: "assets/flags/ae.png" },
  { id: 3, name: "Afghanistan", image: "assets/flags/af.png" },
  { id: 4, name: "Antigua and Barbuda", image: "assets/flags/ag.png" },
  { id: 5, name: "Anguilla", image: "assets/flags/ai.png" },
  { id: 6, name: "Albania", image: "assets/flags/al.png" },
  { id: 7, name: "Armenia", image: "assets/flags/am.png" },
  { id: 8, name: "Angola", image: "assets/flags/ao.png" },
  { id: 9, name: "Antarctica", image: "assets/flags/aq.png" },
  { id: 10, name: "Argentina", image: "assets/flags/ar.png" },
  { id: 11, name: "American Samoa", image: "assets/flags/as.png" },
  { id: 12, name: "Austria", image: "assets/flags/at.png" },
  { id: 13, name: "Australia", image: "assets/flags/au.png" },
  { id: 14, name: "Aruba", image: "assets/flags/aw.png" },
  { id: 15, name: "Åland Islands", image: "assets/flags/ax.png" },
  { id: 16, name: "Azerbaijan", image: "assets/flags/az.png" },
  { id: 17, name: "Bosnia and Herzegovina", image: "assets/flags/ba.png" },
  { id: 18, name: "Barbados", image: "assets/flags/bb.png" },
  { id: 19, name: "Bangladesh", image: "assets/flags/bd.png" },
  { id: 20, name: "Belgium", image: "assets/flags/be.png" },
  { id: 21, name: "Burkina Faso", image: "assets/flags/bf.png" },
  { id: 22, name: "Bulgaria", image: "assets/flags/bg.png" },
  { id: 23, name: "Bahrain", image: "assets/flags/bh.png" },
  { id: 24, name: "Burundi", image: "assets/flags/bi.png" },
  { id: 25, name: "Benin", image: "assets/flags/bj.png" },
  { id: 26, name: "Saint Barthélemy", image: "assets/flags/bl.png" },
  { id: 27, name: "Bermuda", image: "assets/flags/bm.png" },
  { id: 28, name: "Brunei", image: "assets/flags/bn.png" },
  { id: 29, name: "Bolivia", image: "assets/flags/bo.png" },
  { id: 30, name: "Bonaire, Sint Eustatius and Saba", image: "assets/flags/bq.png" },
  { id: 31, name: "Brazil", image: "assets/flags/br.png" },
  { id: 32, name: "Bahamas", image: "assets/flags/bs.png" },
  { id: 33, name: "Bhutan", image: "assets/flags/bt.png" },
  { id: 34, name: "Bouvet Island", image: "assets/flags/bv.png" },
  { id: 35, name: "Botswana", image: "assets/flags/bw.png" },
  { id: 36, name: "Belarus", image: "assets/flags/by.png" },
  { id: 37, name: "Belize", image: "assets/flags/bz.png" },
  { id: 38, name: "Canada", image: "assets/flags/ca.png" },
  { id: 39, name: "Cocos (Keeling) Islands", image: "assets/flags/cc.png" },
  { id: 40, name: "Congo (DRC)", image: "assets/flags/cd.png" },
  { id: 41, name: "Central African Republic", image: "assets/flags/cf.png" },
  { id: 42, name: "Congo (Republic)", image: "assets/flags/cg.png" },
  { id: 43, name: "Switzerland", image: "assets/flags/ch.png" },
  { id: 44, name: "Côte d’Ivoire", image: "assets/flags/ci.png" },
  { id: 45, name: "Cook Islands", image: "assets/flags/ck.png" },
  { id: 46, name: "Chile", image: "assets/flags/cl.png" },
  { id: 47, name: "Cameroon", image: "assets/flags/cm.png" },
  { id: 48, name: "China", image: "assets/flags/cn.png" },
  { id: 49, name: "Colombia", image: "assets/flags/co.png" },
  { id: 50, name: "Costa Rica", image: "assets/flags/cr.png" },
  { id: 51, name: "Cuba", image: "assets/flags/cu.png" },
  { id: 52, name: "Cabo Verde", image: "assets/flags/cv.png" },
  { id: 53, name: "Curaçao", image: "assets/flags/cw.png" },
  { id: 54, name: "Christmas Island", image: "assets/flags/cx.png" },
  { id: 55, name: "Cyprus", image: "assets/flags/cy.png" },
  { id: 56, name: "Czechia", image: "assets/flags/cz.png" },
  { id: 57, name: "Germany", image: "assets/flags/de.png" },
  { id: 58, name: "Djibouti", image: "assets/flags/dj.png" },
  { id: 59, name: "Denmark", image: "assets/flags/dk.png" },
  { id: 60, name: "Dominica", image: "assets/flags/dm.png" },
  { id: 61, name: "Dominican Republic", image: "assets/flags/do.png" },
  { id: 62, name: "Algeria", image: "assets/flags/dz.png" },
  { id: 63, name: "Ecuador", image: "assets/flags/ec.png" },
  { id: 64, name: "Estonia", image: "assets/flags/ee.png" },
  { id: 65, name: "Egypt", image: "assets/flags/eg.png" },
  { id: 66, name: "Western Sahara", image: "assets/flags/eh.png" },
  { id: 67, name: "Eritrea", image: "assets/flags/er.png" },
  { id: 68, name: "Spain", image: "assets/flags/es.png" },
  { id: 69, name: "Ethiopia", image: "assets/flags/et.png" },
  { id: 70, name: "Finland", image: "assets/flags/fi.png" },
  { id: 71, name: "Fiji", image: "assets/flags/fj.png" },
  { id: 72, name: "Falkland Islands", image: "assets/flags/fk.png" },
  { id: 73, name: "Micronesia", image: "assets/flags/fm.png" },
  { id: 74, name: "Faroe Islands", image: "assets/flags/fo.png" },
  { id: 75, name: "France", image: "assets/flags/fr.png" },
  { id: 76, name: "Gabon", image: "assets/flags/ga.png" },
  { id: 77, name: "England", image: "assets/flags/gb-eng.png" },
  { id: 78, name: "Northern Ireland", image: "assets/flags/gb-nir.png" },
  { id: 79, name: "Scotland", image: "assets/flags/gb-sct.png" },
  { id: 80, name: "Wales", image: "assets/flags/gb-wls.png" },
  { id: 81, name: "United Kingdom", image: "assets/flags/gb.png" },
  { id: 82, name: "Grenada", image: "assets/flags/gd.png" },
  { id: 83, name: "Georgia", image: "assets/flags/ge.png" },
  { id: 84, name: "French Guiana", image: "assets/flags/gf.png" },
  { id: 85, name: "Guernsey", image: "assets/flags/gg.png" },
  { id: 86, name: "Ghana", image: "assets/flags/gh.png" },
  { id: 87, name: "Gibraltar", image: "assets/flags/gi.png" },
  { id: 88, name: "Greenland", image: "assets/flags/gl.png" },
  { id: 89, name: "Gambia", image: "assets/flags/gm.png" },
  { id: 90, name: "Guinea", image: "assets/flags/gn.png" },
  { id: 91, name: "Guadeloupe", image: "assets/flags/gp.png" },
  { id: 92, name: "Equatorial Guinea", image: "assets/flags/gq.png" },
  { id: 93, name: "Greece", image: "assets/flags/gr.png" },
  { id: 94, name: "South Georgia and the South Sandwich Islands", image: "assets/flags/gs.png" },
  { id: 95, name: "Guatemala", image: "assets/flags/gt.png" },
  { id: 96, name: "Guam", image: "assets/flags/gu.png" },
  { id: 97, name: "Guinea-Bissau", image: "assets/flags/gw.png" },
  { id: 98, name: "Guyana", image: "assets/flags/gy.png" },
  { id: 99, name: "Hong Kong", image: "assets/flags/hk.png" },
  { id: 100, name: "Heard Island and McDonald Islands", image: "assets/flags/hm.png" },
  { id: 101, name: "Honduras", image: "assets/flags/hn.png" },
  { id: 102, name: "Croatia", image: "assets/flags/hr.png" },
  { id: 103, name: "Haiti", image: "assets/flags/ht.png" },
  { id: 104, name: "Hungary", image: "assets/flags/hu.png" },
  { id: 105, name: "Indonesia", image: "assets/flags/id.png" },
  { id: 106, name: "Ireland", image: "assets/flags/ie.png" },
  { id: 107, name: "Israel", image: "assets/flags/il.png" },
  { id: 108, name: "Isle of Man", image: "assets/flags/im.png" },
  { id: 109, name: "India", image: "assets/flags/in.png" },
  { id: 110, name: "British Indian Ocean Territory", image: "assets/flags/io.png" },
  { id: 111, name: "Iraq", image: "assets/flags/iq.png" },
  { id: 112, name: "Iran", image: "assets/flags/ir.png" },
  { id: 113, name: "Iceland", image: "assets/flags/is.png" },
  { id: 114, name: "Italy", image: "assets/flags/it.png" },
  { id: 115, name: "Jersey", image: "assets/flags/je.png" },
  { id: 116, name: "Jamaica", image: "assets/flags/jm.png" },
  { id: 117, name: "Jordan", image: "assets/flags/jo.png" },
  { id: 118, name: "Japan", image: "assets/flags/jp.png" },
  { id: 119, name: "Kenya", image: "assets/flags/ke.png" },
  { id: 120, name: "Kyrgyzstan", image: "assets/flags/kg.png" },
  { id: 121, name: "Cambodia", image: "assets/flags/kh.png" },
  { id: 122, name: "Kiribati", image: "assets/flags/ki.png" },
  { id: 123, name: "Comoros", image: "assets/flags/km.png" },
  { id: 124, name: "Saint Kitts and Nevis", image: "assets/flags/kn.png" },
  { id: 125, name: "North Korea", image: "assets/flags/kp.png" },
  { id: 126, name: "South Korea", image: "assets/flags/kr.png" },
  { id: 127, name: "Kuwait", image: "assets/flags/kw.png" },
  { id: 128, name: "Cayman Islands", image: "assets/flags/ky.png" },
  { id: 129, name: "Kazakhstan", image: "assets/flags/kz.png" },
  { id: 130, name: "Laos", image: "assets/flags/la.png" },
  { id: 131, name: "Lebanon", image: "assets/flags/lb.png" },
  { id: 132, name: "Saint Lucia", image: "assets/flags/lc.png" },
  { id: 133, name: "Liechtenstein", image: "assets/flags/li.png" },
  { id: 134, name: "Sri Lanka", image: "assets/flags/lk.png" },
  { id: 135, name: "Liberia", image: "assets/flags/lr.png" },
  { id: 136, name: "Lesotho", image: "assets/flags/ls.png" },
  { id: 137, name: "Lithuania", image: "assets/flags/lt.png" },
  { id: 138, name: "Luxembourg", image: "assets/flags/lu.png" },
  { id: 139, name: "Latvia", image: "assets/flags/lv.png" },
  { id: 140, name: "Libya", image: "assets/flags/ly.png" },
  { id: 141, name: "Morocco", image: "assets/flags/ma.png" },
  { id: 142, name: "Monaco", image: "assets/flags/mc.png" },
  { id: 143, name: "Moldova", image: "assets/flags/md.png" },
  { id: 144, name: "Montenegro", image: "assets/flags/me.png" },
  { id: 145, name: "Saint Martin", image: "assets/flags/mf.png" },
  { id: 146, name: "Madagascar", image: "assets/flags/mg.png" },
  { id: 147, name: "Marshall Islands", image: "assets/flags/mh.png" },
  { id: 148, name: "North Macedonia", image: "assets/flags/mk.png" },
  { id: 149, name: "Mali", image: "assets/flags/ml.png" },
  { id: 150, name: "Myanmar (Burma)", image: "assets/flags/mm.png" },
  { id: 151, name: "Mongolia", image: "assets/flags/mn.png" },
  { id: 152, name: "Macau", image: "assets/flags/mo.png" },
  { id: 153, name: "Northern Mariana Islands", image: "assets/flags/mp.png" },
  { id: 154, name: "Martinique", image: "assets/flags/mq.png" },
  { id: 155, name: "Mauritania", image: "assets/flags/mr.png" },
  { id: 156, name: "Montserrat", image: "assets/flags/ms.png" },
  { id: 157, name: "Malta", image: "assets/flags/mt.png" },
  { id: 158, name: "Mauritius", image: "assets/flags/mu.png" },
  { id: 159, name: "Maldives", image: "assets/flags/mv.png" },
  { id: 160, name: "Malawi", image: "assets/flags/mw.png" },
  { id: 161, name: "Mexico", image: "assets/flags/mx.png" },
  { id: 162, name: "Malaysia", image: "assets/flags/my.png" },
  { id: 163, name: "Mozambique", image: "assets/flags/mz.png" },
  { id: 164, name: "Namibia", image: "assets/flags/na.png" },
  { id: 165, name: "New Caledonia", image: "assets/flags/nc.png" },
  { id: 166, name: "Niger", image: "assets/flags/ne.png" },
  { id: 167, name: "Norfolk Island", image: "assets/flags/nf.png" },
  { id: 168, name: "Nigeria", image: "assets/flags/ng.png" },
  { id: 169, name: "Nicaragua", image: "assets/flags/ni.png" },
  { id: 170, name: "Netherlands", image: "assets/flags/nl.png" },
  { id: 171, name: "Norway", image: "assets/flags/no.png" },
  { id: 172, name: "Nepal", image: "assets/flags/np.png" },
  { id: 173, name: "Nauru", image: "assets/flags/nr.png" },
  { id: 174, name: "Niue", image: "assets/flags/nu.png" },
  { id: 175, name: "New Zealand", image: "assets/flags/nz.png" },
  { id: 176, name: "Oman", image: "assets/flags/om.png" },
  { id: 177, name: "Panama", image: "assets/flags/pa.png" },
  { id: 178, name: "Peru", image: "assets/flags/pe.png" },
  { id: 179, name: "French Polynesia", image: "assets/flags/pf.png" },
  { id: 180, name: "Papua New Guinea", image: "assets/flags/pg.png" },
  { id: 181, name: "Philippines", image: "assets/flags/ph.png" },
  { id: 182, name: "Pakistan", image: "assets/flags/pk.png" },
  { id: 183, name: "Poland", image: "assets/flags/pl.png" },
  { id: 184, name: "Saint Pierre and Miquelon", image: "assets/flags/pm.png" },
  { id: 185, name: "Pitcairn Islands", image: "assets/flags/pn.png" },
  { id: 186, name: "Puerto Rico", image: "assets/flags/pr.png" },
  { id: 187, name: "Palestinian Territories", image: "assets/flags/ps.png" },
  { id: 188, name: "Portugal", image: "assets/flags/pt.png" },
  { id: 189, name: "Palau", image: "assets/flags/pw.png" },
  { id: 190, name: "Paraguay", image: "assets/flags/py.png" },
  { id: 191, name: "Qatar", image: "assets/flags/qa.png" },
  { id: 192, name: "Réunion", image: "assets/flags/re.png" },
  { id: 193, name: "Romania", image: "assets/flags/ro.png" },
  { id: 194, name: "Serbia", image: "assets/flags/rs.png" },
  { id: 195, name: "Russia", image: "assets/flags/ru.png" },
  { id: 196, name: "Rwanda", image: "assets/flags/rw.png" },
  { id: 197, name: "Saudi Arabia", image: "assets/flags/sa.png" },
  { id: 198, name: "Solomon Islands", image: "assets/flags/sb.png" },
  { id: 199, name: "Seychelles", image: "assets/flags/sc.png" },
  { id: 200, name: "Sudan", image: "assets/flags/sd.png" },
  { id: 201, name: "Sweden", image: "assets/flags/se.png" },
  { id: 202, name: "Singapore", image: "assets/flags/sg.png" },
  { id: 203, name: "Saint Helena", image: "assets/flags/sh.png" },
  { id: 204, name: "Slovenia", image: "assets/flags/si.png" },
  { id: 205, name: "Svalbard and Jan Mayen", image: "assets/flags/sj.png" },
  { id: 206, name: "Slovakia", image: "assets/flags/sk.png" },
  { id: 207, name: "Sierra Leone", image: "assets/flags/sl.png" },
  { id: 208, name: "San Marino", image: "assets/flags/sm.png" },
  { id: 209, name: "Senegal", image: "assets/flags/sn.png" },
  { id: 210, name: "Somalia", image: "assets/flags/so.png" },
  { id: 211, name: "Suriname", image: "assets/flags/sr.png" },
  { id: 212, name: "South Sudan", image: "assets/flags/ss.png" },
  { id: 213, name: "São Tomé and Príncipe", image: "assets/flags/st.png" },
  { id: 214, name: "El Salvador", image: "assets/flags/sv.png" },
  { id: 215, name: "Sint Maarten", image: "assets/flags/sx.png" },
  { id: 216, name: "Syria", image: "assets/flags/sy.png" },
  { id: 217, name: "Swaziland", image: "assets/flags/sz.png" },
  { id: 218, name: "Turks and Caicos Islands", image: "assets/flags/tc.png" },
  { id: 219, name: "Chad", image: "assets/flags/td.png" },
  { id: 220, name: "French Southern Territories", image: "assets/flags/tf.png" },
  { id: 221, name: "Togo", image: "assets/flags/tg.png" },
  { id: 222, name: "Thailand", image: "assets/flags/th.png" },
  { id: 223, name: "Tajikistan", image: "assets/flags/tj.png" },
  { id: 224, name: "Tokelau", image: "assets/flags/tk.png" },
  { id: 225, name: "Timor-Leste", image: "assets/flags/tl.png" },
  { id: 226, name: "Turkmenistan", image: "assets/flags/tm.png" },
  { id: 227, name: "Tunisia", image: "assets/flags/tn.png" },
  { id: 228, name: "Tonga", image: "assets/flags/to.png" },
  { id: 229, name: "Turkey", image: "assets/flags/tr.png" },
  { id: 230, name: "Trinidad and Tobago", image: "assets/flags/tt.png" },
  { id: 231, name: "Tuvalu", image: "assets/flags/tv.png" },
  { id: 232, name: "Taiwan", image: "assets/flags/tw.png" },
  { id: 233, name: "Tanzania", image: "assets/flags/tz.png" },
  { id: 234, name: "Ukraine", image: "assets/flags/ua.png" },
  { id: 235, name: "Uganda", image: "assets/flags/ug.png" },
  { id: 236, name: "U.S. Minor Outlying Islands", image: "assets/flags/um.png" },
  { id: 237, name: "United States", image: "assets/flags/us.png" },
  { id: 238, name: "Uruguay", image: "assets/flags/uy.png" },
  { id: 239, name: "Uzbekistan", image: "assets/flags/uz.png" },
  { id: 240, name: "Vatican City", image: "assets/flags/va.png" },
  { id: 241, name: "Saint Vincent and the Grenadines", image: "assets/flags/vc.png" },
  { id: 242, name: "Venezuela", image: "assets/flags/ve.png" },
  { id: 243, name: "British Virgin Islands", image: "assets/flags/vg.png" },
  { id: 244, name: "U.S. Virgin Islands", image: "assets/flags/vi.png" },
  { id: 245, name: "Vietnam", image: "assets/flags/vn.png" },
  { id: 246, name: "Vanuatu", image: "assets/flags/vu.png" },
  { id: 247, name: "Wallis and Futuna", image: "assets/flags/wf.png" },
  { id: 248, name: "Samoa", image: "assets/flags/ws.png" },
  { id: 249, name: "Kosovo", image: "assets/flags/xk.png" },
  { id: 250, name: "Yemen", image: "assets/flags/ye.png" },
  { id: 251, name: "Mayotte", image: "assets/flags/yt.png" },
  { id: 252, name: "South Africa", image: "assets/flags/za.png" },
  { id: 253, name: "Zambia", image: "assets/flags/zm.png" },
  { id: 254, name: "Zimbabwe", image: "assets/flags/zw.png" },
];


export default countries;
